# Generated by Django 4.2.3 on 2023-07-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='bottomwear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='topwear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='woolenwear',
            field=models.IntegerField(),
        ),
    ]
