# Generated by Django 4.2.3 on 2023-08-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryadmin', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fav_icon',
            field=models.ImageField(blank=True, null=True, upload_to='company_fav_icons/'),
        ),
    ]
