# Generated by Django 4.2.3 on 2023-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryadmin', '0004_company_fav_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comapny_name',
            field=models.CharField(default='laundry', max_length=100),
        ),
    ]
