# Generated by Django 4.2.3 on 2023-08-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundryadmin', '0005_alter_company_comapny_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
