# Generated by Django 4.2.3 on 2023-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryadmin', '0007_rename_company_name_company_comapny_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='bottomwear',
            field=models.IntegerField(default='25'),
        ),
        migrations.AlterField(
            model_name='price',
            name='topwear',
            field=models.IntegerField(default='25'),
        ),
        migrations.AlterField(
            model_name='price',
            name='woolenwear',
            field=models.IntegerField(default='25'),
        ),
    ]
