# Generated by Django 4.2.3 on 2023-07-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_name_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
