# Generated by Django 4.2.3 on 2023-07-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReqeuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('topwear', models.PositiveIntegerField(default=0)),
                ('bottomwear', models.PositiveIntegerField(default=0)),
                ('woolenwear', models.PositiveIntegerField(default=0)),
                ('otherclothes', models.PositiveIntegerField(default=0)),
                ('service_type', models.CharField(choices=[('drop', 'Drop'), ('pickup', 'House Pickup')], max_length=10)),
                ('contact_person', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
