# Generated by Django 4.2.3 on 2023-07-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userreqeuest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreqeuest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreqeuest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
