# Generated by Django 4.2.3 on 2023-07-28 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_userreqeuest_address_alter_userreqeuest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreqeuest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
