# Generated by Django 4.2.3 on 2023-07-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userreqeuest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreqeuest',
            name='progress',
            field=models.CharField(choices=[('accept', 'Accept'), ('inprogress', 'Inprogress'), ('finish', 'Finish')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
