# Generated by Django 4.2.3 on 2023-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userreqeuest_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreqeuest',
            name='progress',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('inprogress', 'Inprogress'), ('finish', 'Finish')], max_length=10),
        ),
    ]
