# Generated by Django 4.2.3 on 2023-07-29 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userreqeuest_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreqeuest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
