# Generated by Django 4.2.3 on 2023-07-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userreqeuest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreqeuest',
            name='totalprice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userreqeuest',
            name='progress',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('inprogress', 'Inprogress'), ('finish', 'Finish'), ('cancle', 'Cancel')], max_length=10),
        ),
    ]
