# Generated by Django 4.2.3 on 2023-07-29 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_userreqeuest_bottomwearprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreqeuest',
            name='id',
        ),
        migrations.AddField(
            model_name='userreqeuest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b814944c-036c-4680-aa3e-a4cc77d1efde'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9b15d458-02b8-41d8-985c-67f327fabdef'), editable=False, primary_key=True, serialize=False),
        ),
    ]
