# Generated by Django 4.2.3 on 2023-07-31 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_userreqeuest_id_userreqeuest_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4f9138f6-998d-4ab1-a095-ec232560a684'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userreqeuest',
            name='progress',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Inprogress', 'Inprogress'), ('Finish', 'Finish'), ('Cancle', 'Cancel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userreqeuest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cf952f89-c078-4c5c-aa9f-046f6f5e9332'), editable=False, primary_key=True, serialize=False),
        ),
    ]
