# Generated by Django 4.2.3 on 2023-07-31 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_profile_uuid_alter_userreqeuest_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f07be42a-eb15-41f9-bade-ccc57c535734'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userreqeuest',
            name='progress',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Inprogress', 'Inprogress'), ('Finish', 'Finish'), ('Cancle', 'Cancle')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userreqeuest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('29218678-c35f-44d8-bcfc-fefdb67d9033'), editable=False, primary_key=True, serialize=False),
        ),
    ]
