# Generated by Django 4.2.3 on 2023-07-31 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_profile_uuid_alter_userreqeuest_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1a697b71-afc2-4e0e-abff-a795b33bc69a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userreqeuest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
