# Generated by Django 4.2.3 on 2023-07-31 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_profile_uuid_alter_userreqeuest_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreqeuest',
            name='payment',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Cash', 'Cash'), ('Online', 'Online')], default='Unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b2081545-be81-4b48-817c-e50b46d3b455'), editable=False, primary_key=True, serialize=False),
        ),
    ]
