# Generated by Django 4.2.3 on 2023-08-01 05:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_profile_uuid_alter_userreqeuest_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc3d3a6d-2dda-49c4-8f32-1f1192f13862'), editable=False, primary_key=True, serialize=False),
        ),
    ]
