# Generated by Django 4.2.3 on 2023-08-01 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5d02c5ee-86fe-4e23-9732-6336e2e68e8c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
