# Generated by Django 4.2.3 on 2023-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_profile_is_verified_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(default=1345, max_length=100),
            preserve_default=False,
        ),
    ]
