# Generated by Django 4.2.3 on 2023-08-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_rename_user_profile_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
